# Generated by Django 3.2.6 on 2021-09-16 08:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('building_name_or_number', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('city_or_town', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=8)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('uprn', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
