# Generated by Django 4.0.8 on 2022-11-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='uprn',
            field=models.PositiveBigIntegerField(default=0, verbose_name='UPRN'),
        ),
    ]
