# Generated by Django 3.2.6 on 2021-09-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0002_marker_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='linked_document',
            field=models.URLField(default=''),
        ),
    ]
