# Generated by Django 3.2.6 on 2021-09-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0003_marker_linked_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='uprn',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
