# Generated by Django 3.2.6 on 2021-09-16 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('markers', '0004_marker_uprn'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation'),
        ),
    ]
