# Generated by Django 3.2.6 on 2021-09-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0005_marker_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='classification_or_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='marker',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marker',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='reference_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
