# Generated by Django 3.2.6 on 2021-09-16 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0006_auto_20210916_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
