# Generated by Django 4.0.2 on 2022-02-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0007_marker_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Risk Title'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='uprn',
            field=models.PositiveBigIntegerField(default=0, verbose_name='UPRN'),
        ),
    ]
